[package]
name = "doubuff"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
terminal-vec2 = { git = "https://github.com/oranellis/terminal-vec2-rs.git", tag = "v0.1.0", version = "0.1.0" }
